CREATE DATABASE DoGoMyNghe
go
use DoGoMyNghe

--Tạo bảng khách hàng

CREATE TABLE KHACHHANG(
	MAKH CHAR(10) PRIMARY KEY, --MAKH SINH TU DONG
    TENKH NVARCHAR(50) NOT NULL,
    SDT CHAR(10) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL,
)

--TẠO BẢNG NHÂN VIÊN

CREATE TABLE NHANVIEN
(
	MANV CHAR(10) PRIMARY KEY,
    MATKHAU CHAR(10) NOT NULL,
    TENNV NVARCHAR(50) NOT NULL,
	SDT CHAR(10) NOT NULL,
    NGAYSINH DATETIME NOT NULL,
	DIACHI TEXT,
	EMAIL VARCHAR(100) NOT NULL
)

--TẠO BẢNG DANH MỤC
CREATE TABLE DANHMUC
(
	MADM CHAR(10) PRIMARY KEY,
	TENDM NVARCHAR(50) NOT NULL,
)


--TẠO BẢNG SẢN PHẨM
 
 CREATE TABLE SANPHAM
 (
	MADM CHAR(10) NOT NULL FOREIGN KEY REFERENCES	 DANHMUC(MADM)
   ON DELETE CASCADE ON UPDATE CASCADE,
	 MASP CHAR(10) PRIMARY KEY,
    TENSP NVARCHAR(50)NOT NULL,
	MOTA TEXT,
	GIABAN FLOAT,
	SOLUONG INT,
 )

 --TẠO BẢNG HÓA ĐƠN BÁN
CREATE TABLE HOADONBAN
 (
	 MAHDB CHAR(10) PRIMARY KEY,
    NGAYBAN DATETIME NOT NULL,
	 MADM CHAR(10) NOT NULL FOREIGN KEY REFERENCES	 DANHMUC(MADM),
    MASP CHAR(10) NOT NULL FOREIGN KEY REFERENCES SANPHAM(MASP)
   ON DELETE CASCADE ON UPDATE CASCADE,
     MANV CHAR(10) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MANV)
   ON DELETE CASCADE ON UPDATE CASCADE,
    MAKH CHAR(10) NOT NULL FOREIGN KEY REFERENCES KHACHHANG(MAKH)
   ON DELETE CASCADE ON UPDATE CASCADE,
 )

 --CHI TIẾT HÓA ĐƠN BÁN
 CREATE TABLE CHITIETHDB
 (
	MAHDB CHAR(10) NOT NULL FOREIGN KEY REFERENCES HOADONBAN(MAHDB)
   ON DELETE CASCADE ON UPDATE CASCADE,
   TENNV NVARCHAR(50) NOT NULL,
   TENKH NVARCHAR(50) NOT NULL,
   TENDM NVARCHAR(50) NOT NULL,
   TENSP NVARCHAR(50) NOT NULL,
    SOLUONG INT,
	GIABAN FLOAT,
	TONGTIEN FLOAT
 )
 select * from KHACHHANG

 INSERT INTO KHACHHANG VALUES('KH1',N'VƯƠNG ĐỨC TUẤN','0135451251',N'CẨM GIÀNG-HẢII DƯƠNG','vuongductuan@gmail.com')
INSERT INTO KHACHHANG VALUES('KH2',N'NGUYỄN VĂN TRƯỜNG','0153541252',N'KHOÁI CHÂU-HƯNG YÊN')
INSERT INTO KHACHHANG VALUES('KH3',N'ĐINH QUỐC TRUNG','0135541254',N'THÀNH PHỐ HƯNG YÊN')
INSERT INTO KHACHHANG VALUES('KH4',N'PHẠM TIẾN THÀNH','0135454251',N'ÂN THI-HƯNG YÊN')
INSERT INTO KHACHHANG VALUES('KH5',N'HOÀNG NGUYỆT NHI','0135541251',N'ÂN THI-HƯNG YÊN')
INSERT INTO KHACHHANG VALUES('KH6',N'VŨ MINH HIẾU','0130012551',N'PHÚ THỌ')
INSERT INTO KHACHHANG VALUES('KH7',N'DƯƠNG ĐỨC NGUYÊN','0135541111',N'THÀNH PHỐ HƯNG YÊN')
INSERT INTO KHACHHANG VALUES('KH8',N'VƯƠNG ĐỨC DŨNG','0135415251',N'CẨM GIÀNG-HẢI DƯƠNG')
INSERT INTO KHACHHANG VALUES('KH9',N'PHẠM THỊ ÁNH NGỌC','0135441251',N'NINH BÌNH')
INSERT INTO KHACHHANG VALUES('KH10',N'NGUYỂN THÚY HIỀN','0134541231',N'KHOÁI CHÂU-HƯNG YÊN')